export const bag = [
    {id:1,
     img: "/images/product/s.jpg" ,
     type: "Shoes",
     product: 'Winter Collection',
     productId:"438240e",
     size: "37.5",
     price:"40"
    },
    {id:2,
        img: "/images/product/s1.jpg" ,
        type: "Shoes",
        product: 'Winter Collection',
        productId:"314245t",
        size: "37.5",
        price:"415"
       },
       {id:3,
        img: "/images/product/s3.jpg" ,
        type: "Shoes",
        product: 'Winter Collection',
        productId:"S3412rdh",
        size: "37.5",
        price:"445"
       },
       {id:4,
        img: "/images/product/s3.jpg" ,
        product: 'Winter Collection',
        type: "Shoes",
        productId:"S342142ea",
        size: "37.5",
        price:"425"
       },
       {id:5,
        img: "/images/product/s4.jpg" ,
        product: 'Winter Collection',
        type: "Shoes",
        productId:"ddsad134",
        size: "37.5",
        price:"45"
       },
]